### ISSUE TITLE
Implement "native" leader selection using cosmos-sdk staking module

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#207] opened 2021-12-07 17:02 UTC

**Comment by liamsi** [comment] 2021-12-08 17:47
ref: https://github.com/celestiaorg/optimint/issues/18

**Comment by Manav-Aggarwal** [comment] 2023-09-11 16:47
Duplicate of https://github.com/rollkit/rollkit/issues/815

**Closed by Manav-Aggarwal** 2023-09-11 16:47 UTC
