### ISSUE TITLE
Fullnode after generating the fraud proof does not immediately force stop the node

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/rollkit#947] opened 2023-05-19 01:01 UTC
The fullnode after generating and broadcasting the fraud proof, exists the SyncLoop silently and upon receiving the gossiped fraud proof, cancels the context. This could lead to fullnode never stopping gracefully. This can be fixed partially by capturing the cancel event (which only happens upon receiving the fraud proof) and stopping the node gracefully. 

```
func (n *FullNode) OnStart() error {
  ...
  ...
  go func(ctx context.Context) {
		  select {
		  case <-ctx.Done():
			  n.Stop()
		  default:
		  }
  }(n.ctx)
  return nil
}
```

**Comment by Manav-Aggarwal** [comment] 2024-06-27 21:37
Duplicate of https://github.com/rollkit/rollkit/issues/933

**Closed by Manav-Aggarwal** 2024-06-27 21:37 UTC
Labels: C:state-fraud-proofs, blocked
