### ISSUE TITLE
Unsafe ctx.Done assumption in publishBlock

### ISSUE THREAD

**Issue by newTendermint** [rollkit/rollkit#1488] opened 2024-01-17 22:06 UTC
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-27a864c0-7fff-48a2-1426-bba5277c8030"><h3 dir="ltr" style="line-height:1.38;margin-top:16pt;margin-bottom:4pt;"><span style="font-size:13.999999999999998pt;font-family:Roboto,sans-serif;color:#434343;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Finding 021 - Unsafe ctx.Done assumption in publishBlock</span></h3><div dir="ltr" style="margin-left:0pt;" align="left">
ID | 021
-- | --
Finding | Unsafe ctx.Done assumption in publishBlock
Severity | 0 - Informational
Description | Between the select evaluation and the next channel send, the ctx might have become done.
Recommendation | Look finding 022
Code References | https://github.com/rollkit/rollkit/blob/eccdd0f1793a5ac532011ef4d896de9e0d8bcb9d/block/manager.go#L753 <- evaluationhttps://github.com/rollkit/rollkit/blob/eccdd0f1793a5ac532011ef4d896de9e0d8bcb9d/block/manager.go#L760 <- when the CTX might have become done

</div></b>

**Comment by Manav-Aggarwal** [comment] 2024-01-18 15:45
Duplicate of https://github.com/rollkit/rollkit/issues/1476.

**Closed by Manav-Aggarwal** 2024-01-18 15:45 UTC
Labels: needs-triage
