### ISSUE TITLE
[Feature Request]: investigate and gracefully handle data availability layer tx failure

### ISSUE THREAD

**Issue by tuxcanfly** [rollkit/rollkit#1169] opened 2023-09-05 15:59 UTC
### Implementation ideas

Need to investigate how rollkit deals with transient tx failures (e.g: celestia transactions failing with `account sequence mismatch`) and gracefully handle retries.

**Comment by Manav-Aggarwal** [comment] 2024-06-18 23:27
Duplicate of https://github.com/rollkit/rollkit/issues/1522

**Closed by Manav-Aggarwal** 2024-06-18 23:27 UTC
Labels: T:da-integration
