### ISSUE TITLE
Unnecessary Usage of SyncerStatus

### ISSUE THREAD

**Issue by newTendermint** [rollkit/rollkit#1481] opened 2024-01-17 21:57 UTC
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-1e2f8cb0-7fff-068d-a36c-d7a95745a49a"><div dir="ltr" style="margin-left:0pt;" align="left">
ID | 001
-- | --
Finding | Unnecessary Usage of SyncerStatus
Severity | 1 - Informational
Description | The SyncerStatus type is used to synchronize access to a boolean indicating the status of syncing. This proprietary type is not needed as you can just use the sync/atomic stdlib package to achieve the same thing, which results in less code being maintained.
Recommendation | Consider using sync/atomic stdlib in place of SyncerStatus.
Code References | https://github.com/rollkit/rollkit/blob/eccdd0f1793a5ac532011ef4d896de9e0d8bcb9d/block/syncer_status.go

</div></b>

**Comment by Manav-Aggarwal** [comment] 2024-01-18 15:50
Duplicate of https://github.com/rollkit/rollkit/issues/1457

**Closed by Manav-Aggarwal** 2024-01-18 15:50 UTC
Labels: needs-triage
