### ISSUE TITLE
Misuse of context

### ISSUE THREAD

**Issue by newTendermint** [rollkit/rollkit#1493] opened 2024-01-17 22:13 UTC
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-c77537e2-7fff-9d14-0117-8ddd9bd460df"><h3 dir="ltr" style="line-height:1.38;margin-top:16pt;margin-bottom:4pt;"><span style="font-size:13.999999999999998pt;font-family:Roboto,sans-serif;color:#434343;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Finding 029 - Misuse of context&nbsp;</span></h3><div dir="ltr" style="margin-left:0pt;" align="left">
ID | 029
-- | --
Finding | Misuse of context
Severity | 0 - Informational
Description | Context is meant to be scoped around the lifecycle of a single request, not the lifecycle of the entire program. Contexts are not designed for storing global or long-lived data. They are meant to be passed down the call chain and should not be stored in global or package-level variables.
Recommendation | Remove context from the DefaultStore struct, make the Store interface methods accept context.
Code References | https://github.com/rollkit/rollkit/blob/eccdd0f1793a5ac532011ef4d896de9e0d8bcb9d/store/store.go#L33https://github.com/rollkit/rollkit/blob/eccdd0f1793a5ac532011ef4d896de9e0d8bcb9d/store/types.go#L21 <- Example of refactor where to introduce context as a param.

</div></b>

**Comment by Manav-Aggarwal** [comment] 2024-01-18 15:42
Duplicate of https://github.com/rollkit/rollkit/issues/1453, already resolved.

**Closed by Manav-Aggarwal** 2024-01-18 15:42 UTC
Labels: needs-triage
