### ISSUE TITLE
Ensure data retrieval is functioning properly for rollkit

### ISSUE THREAD

**Issue by jcstein** [rollkit/rollkit#929] opened 2023-05-10 15:42 UTC
in the past, i’ve seen behavior on rollkit where rollkit thinks that it is posting data (submitting PFDs instead of PFBs, and running “normally”). due to this, I believe the check on retrieving data may not be 100% sound

i suspect a part of the check on data retrieval is not working properly, even on newer versions of rollkit. this was brought up again, because on BSR, there are many rollups running, but the retrieval of namespaced data on `celestia-node` is not working properly. so how are these rollups running?

if you go to [this issue](https://github.com/rollkit/rollkit/issues/792) and this heading “`node main:latest + core/app v0.12.0 + rollkit/cosmos-sdk@v0.46.7-rollkit-v0.7.0-no-fraud-proofs`”, you’ll see some[ links to logs](https://app.warp.dev/block/NFB9I9THQW35e9gNMZH70V) where the rollup is running, but not posting data and `daHeight=0`, but still producing new rollup blocks, throwing no errors

**Comment by nashqueue** [comment] 2023-05-12 09:46
This issue might be related to the sequencer posting to Celestia, but it already has the data locally. If a Full Node is syncing from Celestia, it would be unable to retrieve anything and throw the appropriate error / intended behaviour.

**Comment by nashqueue** [comment] 2023-05-19 16:44
This needs to be tested when ensuring compatibility with celestia node 0.92+ while or after resolving #943

**Comment by Manav-Aggarwal** [comment] 2023-11-16 11:51
Closing this, duplicate of https://github.com/rollkit/rollkit/issues/1236

**Closed by Manav-Aggarwal** 2023-11-16 11:51 UTC
Labels: T:bug, P:high, va
