### ISSUE TITLE
Timeout reported by broadcastTxCommit

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#194] opened 2021-11-24 11:14 UTC
When executing transfer with `demoappd`, I see following errors:
```
ERR Error on broadcastTxCommit err="timed out waiting for tx to be included in a block" module=events
```

Error is also returned to the client:
```
Error: RPC error -32000 - timed out waiting for tx to be included in a block
```

Transfer is successful (can confirm balance change), but reported as timeout. This may be related to custom block time, or some issues with event bus.

**Comment by liamsi** [comment] 2021-12-01 17:03
related:

- https://github.com/celestiaorg/celestia-core/blob/1609bde2a41604fff1ebcb202e0e9cce1048fb3b/config/config.go#L479-L483
- https://github.com/celestiaorg/celestia-core/blob/0ed8dba99189e3dfd960a8945192c6146c47dc9d/rpc/core/mempool.go#L123

So could just try to make this roughly the block time instead.

**Comment by Manav-Aggarwal** [comment] 2023-09-11 16:42
Duplicate of https://github.com/rollkit/rollkit/issues/1036

**Closed by Manav-Aggarwal** 2023-09-11 16:42 UTC
Labels: T:bug
