### ISSUE TITLE
Decide on type of height related fields

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#688] opened 2023-01-17 08:10 UTC
Original implementation used `uint64` to represent any type of `height`. This seems to be the most appropriate type.
The convention in Tendermint/Cosmos-SDK is to use `int64`. The same for `go-header` library.

We need to decide what type should be used and change the code accordingly.

**Comment by Wondertan** [comment] 2023-01-18 09:08
Note that go-header’s int usage is not a requirement, and we can change it if needed.

**Comment by Manav-Aggarwal** [comment] 2023-09-12 16:35
Duplicate of https://github.com/rollkit/rollkit/issues/1176

**Closed by Manav-Aggarwal** 2023-09-12 16:35 UTC
Labels: T:code-hygiene
