### ISSUE TITLE
Look at how to refactor this to not be duplicating `createNodes`

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1703] opened 2024-06-12 12:54 UTC
Look at how to refactor this to not be duplicating `createNodes`

_Originally posted by @MSevey in https://github.com/rollkit/rollkit/pull/1690#discussion_r1636414334_

**Comment by Manav-Aggarwal** [comment] 2024-06-27 20:44
Duplicate of https://github.com/rollkit/rollkit/issues/1648

**Closed by Manav-Aggarwal** 2024-06-27 20:44 UTC
Labels: T:code-hygiene
