### ISSUE TITLE
`InitialBlockHeight` is handled incorrectly

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#699] opened 2023-01-19 08:29 UTC
In `publishBlock` block number is always retrieved from store, and `InitialBlockHeight` from genesis is ignored. But the, few lines below height is actually compared to `InitialBlockHeight`, which makes no sense.

https://github.com/celestiaorg/rollmint/blob/008281cfd6e668e85e287cd7dcd4cbb6d3aea746/block/manager.go#L427-L433

We should make sure that `InitialBlockHeight` from genesis is properly used for first block.

**Comment by Manav-Aggarwal** [comment] 2024-03-14 18:53
Duplicate of https://github.com/rollkit/rollkit/issues/1360

**Closed by Manav-Aggarwal** 2024-03-14 18:53 UTC
Labels: T:bug, va
