### ISSUE TITLE
Create how-to describing implementation of DA layer client

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#74] opened 2021-06-03 18:34 UTC
It is important to describe how to implement new Data Availability layer client and use it with Optimint.
It can be a tutorial, step-by-step guide, detailed example or even very precise package-level godoc.

**Comment by Manav-Aggarwal** [comment] 2023-09-11 16:27
Blocked on: https://github.com/rollkit/rollkit/issues/1122

**Comment by nashqueue** [comment] 2023-09-11 16:31
Duplicate of https://github.com/rollkit/docs/issues/253

**Closed by nashqueue** 2023-09-11 16:31 UTC
Labels: T:documentation
