### ISSUE TITLE
Sequencer submits 2 blocks at the same height.

### ISSUE THREAD

**Issue by nashqueue** [rollkit/rollkit#871] opened 2023-04-17 14:21 UTC
Sequencer submits 2 blocks at the same height h but with different content. 

Current Expected Behaviour: We take FCFS as a fork choice rule.
But wished behaviour: Sequencer gets slashed or maybe fullnodes should halt

**Comment by Manav-Aggarwal** [comment] 2023-09-12 15:56
cc: @S1nus

**Comment by Manav-Aggarwal** [comment] 2024-06-18 23:15
Duplicate of https://github.com/rollkit/rollkit/issues/1672

**Closed by Manav-Aggarwal** 2024-06-18 23:15 UTC
Labels: T:testing, P:high, C: sequencing, v1
