### ISSUE TITLE
Error in uploading block information to DA layer when there are two transactions in one block

### ISSUE THREAD

**Issue by stompesi** [rollkit/rollkit#1001] opened 2023-06-09 12:57 UTC
I was trying to run the [gm-world](https://rollkit.dev/docs/tutorials/gm-world/).

## Run DA
So I used the local-celestia-devnet:v0.9.1 as shown in the figure.
![image](https://github.com/rollkit/rollkit/assets/1393421/6554a369-af4e-4272-8ac4-ccc9b5a1649e)
This picture shows the guideline in [the document](https://rollkit.dev/docs/tutorials/gm-world/).

![image](https://github.com/rollkit/rollkit/assets/1393421/60553712-7c91-4037-9890-d1dc8454b449)

This picture shows that I replaced the modules.

## Replace the modules
Also I changed go modules. (You can see the module version.) 
![image](https://github.com/rollkit/rollkit/assets/1393421/3a70e0bb-d8b7-4f8c-ab78-cd502d826cbc)
This picture shows the guideline in [the document](https://rollkit.dev/docs/tutorials/gm-world/).

<img width="1197" alt="image" src="https://github.com/rollkit/rollkit/assets/1393421/b7c02e93-7fef-4e53-86f9-6ca8707df2ba">
This picture shows that I replaced the modules.

When I tried to send a coin with just one transaction. It worked. (as shown in the figure)
<img width="1719" alt="image" src="https://github.com/rollkit/rollkit/assets/1393421/4d143e79-fc3a-40b5-8e05-cd43bf757dd6">

# However, when I tried to send coins simultaneously with two different transactions (manullay). Rollkit didn't work. (as picture shown)

<img width="1524" alt="image" src="https://github.com/rollkit/rollkit/assets/1393421/ed9e1653-f081-4b2b-850f-1d71526b823c">
(send two transactions)

![image](https://github.com/rollkit/rollkit/assets/1393421/225488d7-d753-4cef-af2a-ca939fb9b837)
(it shows that the rollkit error)

And finally the error is like this.
<img width="866" alt="image" src="https://github.com/rollkit/rollkit/assets/1393421/ec29c7c5-8f3c-48c3-9f83-f05eba21e243">

```bash
12:43PM ERR DA layer submission failed error="rpc error: code = Unknown desc = timed out waiting for tx to be included in a block" attempt=1 module=BlockManager
12:43PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=2 module=BlockManager
12:43PM ERR DA layer submission failed error="rpc error: code = Unknown desc = timed out waiting for tx to be included in a block" attempt=1 module=BlockManager
12:43PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=2 module=BlockManager
12:43PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=3 module=BlockManager
12:43PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=4 module=BlockManager
12:43PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=5 module=BlockManager
12:43PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=6 module=BlockManager
12:43PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=7 module=BlockManager
12:43PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=8 module=BlockManager
12:43PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=9 module=BlockManager
12:43PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=10 module=BlockManager
12:45PM ERR DA layer submission failed error="rpc error: code = Unknown desc = timed out waiting for tx to be included in a block" attempt=11 module=BlockManager
12:45PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=12 module=BlockManager
12:47PM ERR DA layer submission failed error="rpc error: code = Unknown desc = timed out waiting for tx to be included in a block" attempt=13 module=BlockManager
12:47PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=14 module=BlockManager
12:47PM ERR failed to retrieve block from DALC daHeight=689579 errors="failed to retrieve block: Get \"http://147.46.240.248:26659/namespaced_data/158120313bf5c3e7/height/689579\": context deadline exceeded (Client.Timeout exceeded while awaiting headers); failed to retrieve block: Get \"http://147.46.240.248:26659/namespaced_data/158120313bf5c3e7/height/689579\": context deadline exceeded (Client.Timeout exceeded while awaiting headers); failed to retrieve block: Get \"http://147.46.240.248:26659/namespaced_data/158120313bf5c3e7/height/689579\": context deadline exceeded (Client.Timeout exceeded while awaiting headers); failed to retrieve block: Get \"http://147.46.240.248:26659/namespaced_data/158120313bf5c3e7/height/689579\": context deadline exceeded (Client.Timeout exceeded while awaiting headers); failed to retrieve block: Get \"http://147.46.240.248:26659/namespaced_data/158120313bf5c3e7/height/689579\": context deadline exceeded (Client.Timeout exceeded while awaiting headers); failed to retrieve block: Get \"http://147.46.240.248:26659/namespaced_data/158120313bf5c3e7/height/689579\": context deadline exceeded (Client.Timeout exceeded while awaiting headers); failed to retrieve block: Get \"http://147.46.240.248:26659/namespaced_data/158120313bf5c3e7/height/689579\": context deadline exceeded (Client.Timeout exceeded while awaiting headers); failed to retrieve block: Get \"http://147.46.240.248:26659/namespaced_data/158120313bf5c3e7/height/689579\": context deadline exceeded (Client.Timeout exceeded while awaiting headers); failed to retrieve block: context deadline exceeded; failed to retrieve block: Get \"http://147.46.240.248:26659/namespaced_data/158120313bf5c3e7/height/689579\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" module=BlockManager
12:48PM ERR DA layer submission failed error="rpc error: code = Unknown desc = timed out waiting for tx to be included in a block" attempt=15 module=BlockManager
12:49PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=16 module=BlockManager
12:50PM ERR DA layer submission failed error="rpc error: code = Unknown desc = timed out waiting for tx to be included in a block" attempt=17 module=BlockManager
12:51PM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=18 module=BlockManager
```

What's wrong with this? Is it possible to solve it right away?

**Comment by gupadhyaya** [comment] 2023-06-09 13:55
@stompesi did u try restart your rollup? `context deadline exceeded` generally means the network issue. nothing specific to rollkit. let us know if restart helps.

**Comment by stompesi** [comment] 2023-06-10 06:13
@gupadhyaya hi!

The problem occurs the first time I do the network. 
Also, the same problem occurs when I restart the rollkit.

I think it's a problem that occurs when the block size increases. It works fine when the block contains a single transaction. However, if 2 transactions are included in a block, the problem continues to occur.


<img width="1728" alt="image" src="https://github.com/rollkit/rollkit/assets/1393421/db9c90dd-c5e7-4e5c-bb58-49452e5ce253">
(When I restart the rollkit, It occurs error)

**Comment by stompesi** [comment] 2023-06-10 06:24
I think it is celestia's problem. Because, when I lookup a block, the rollkit provides the block (two transactions are included). But, when the rollkit submit the block to DA. The DA cant serve.

@gupadhyaya Can you check the (docker) celestia version?

**Comment by gupadhyaya** [comment] 2023-06-12 16:08
@stompesi thanks for providing more details. will take a look and get back to you.

**Comment by stompesi** [comment] 2023-06-13 00:42
Okay. Thanks a lot~

**Comment by gupadhyaya** [comment] 2023-06-23 02:44
@stompesi sorry for the delay in my response. however, I am still unable to reproduce your issue. I tried the exact same configurations that you provided. 
i did run into sequence mismatch issue (due to nonce): `raw_log: 'account sequence mismatch, expected 5, got 4: incorrect account sequence'` when i fired two transactions. however this is not rollkit issue.
note that, i did run into rollkit unable to sync the DA blocks. However this issue is fixed in the rollkit v0.8.1
```9:42PM ERR failed to retrieve block from DALC daHeight=52 errors="failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found; failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found; failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found; failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found; failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found; failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found; failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found; failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found; failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found; failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found" module=BlockManager```

what i can recommend is use the latest rollkit and see if you are still running into issues. let us know. we have listed the versions and their compatible networks in rollkit README: https://github.com/rollkit/rollkit/blob/main/README.md

**Comment by gupadhyaya** [comment] 2023-06-23 02:47
@stompesi there is a nonce issue that is currently being address in the celestia-node: https://github.com/celestiaorg/celestia-node/issues/2389, however this only happens when you have multiple txs from the same account submitted from rollup that are priced differently than the sequence numbers. i don't think your issue of multiple txs is related to that. but do let us know if you think so.

**Comment by gupadhyaya** [comment] 2023-09-11 21:20
closing this as there is no follow-up. @stompesi please feel free to re-open if the issue still persist.

**Closed by gupadhyaya** 2023-09-11 21:20 UTC
Labels: T:da-integration, va
