### ISSUE TITLE
Revisit New methods in types package

### ISSUE THREAD

**Issue by MSevey** [rollkit/rollkit#1325] opened 2023-11-09 17:35 UTC
The `New` method is added to the `Block` struct. This method seems unnecessary as it simply returns a new instance of `Block`. This can be done directly with `new(Block)`. Consider removing this method to reduce complexity.
```diff
- // New returns a new Block.
- func (b *Block) New() *Block {
- 	return new(Block)
- }
```

---

<details>
<summary>Commitable suggestion (Beta)</summary>

```suggestion
// New returns a new Block.
func NewBlock() *Block {
	return new(Block)
}
```

</details>

_Originally posted by @coderabbitai[bot] in https://github.com/rollkit/rollkit/pull/1294#discussion_r1377393911_

**Comment by MSevey** [comment] 2023-11-09 17:36
https://github.com/rollkit/rollkit/pull/1294#discussion_r1377393919

**Comment by MSevey** [comment] 2023-11-09 17:36
https://github.com/rollkit/rollkit/pull/1294#discussion_r1377393929

**Comment by Manav-Aggarwal** [comment] 2023-11-15 14:53
Duplicate of https://github.com/rollkit/rollkit/issues/1340

**Closed by Manav-Aggarwal** 2023-11-15 14:53 UTC
Labels: needs-triage
