### ISSUE TITLE
Implement `Data.ValidateBasic`

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#626] opened 2022-11-23 12:10 UTC
Currently there is no validation in `ValidateBasic` method of block `Data`.
https://github.com/celestiaorg/rollmint/blob/3a518be702b3d4183deb888fbc7958fcc2c3b2bc/types/validation.go#L38-L42

Methods should check:
- [ ] Number of ISRs corresponds to number of TXs
- [ ] ISR's are valid hashes (length is OK)

**Comment by Manav-Aggarwal** [comment] 2024-06-19 00:07
Related: https://github.com/rollkit/rollkit/issues/1271

**Comment by Manav-Aggarwal** [comment] 2024-06-27 21:34
Duplicate of https://github.com/rollkit/rollkit/issues/1271

**Closed by Manav-Aggarwal** 2024-06-27 21:34 UTC
Labels: T:enhancement, C:state-fraud-proofs
